kind: pipeline
name: VerifyCode
type: docker

trigger:
  event:
    - push
    - tag

volumes:
  - name: pnpm-store
    host:
      path: /app/.pnpm-store
steps:
  - name: verify
    image: cicdtools/pipeline-runner
    pull: if-not-exists
    volumes:
      - name: pnpm-store
        path: /root/.pnpm-store
    environment:
      NEXUS_DEPLOYER_USERNAME:
        from_secret: NEXUS_DEPLOYER_USERNAME
      NEXUS_DEPLOYER_PASSWORD:
        from_secret: NEXUS_DEPLOYER_PASSWORD
    commands:
      - pnpm install
      - pnpm prettier:check

---
kind: pipeline
name: PublishArtifacts
type: docker

trigger:
  event:
    - push
    - tag
  ref:
    - refs/heads/dev
    - refs/heads/prerelease/*
    - refs/heads/*.*.x
    - refs/tags/*
depends_on:
  - VerifyCode

volumes:
  - name: pnpm-store
    host:
      path: /app/.pnpm-store
steps:
  - name: download-dockerfile
    image: cicdtools/pipeline-runner
    pull: if-not-exists
    commands:
      - wget -O ./Dockerfile https://raw.githubusercontent.com/KnowHowDevOps/homelab-operations-pipeline/dev/resources/Nginx.dockerfile

  - name: build-docs
    image: cicdtools/pipeline-runner
    pull: if-not-exists
    commands:
      - pnpm install
      - pnpm docs:build

  - name: build-container
    image: plugins/docker
    settings:
      dockerfile: ./Dockerfile
      context: ./
      storage_driver: vfs
      username:
        from_secret: SVC_CONTAINER_REGISTRY_USERNAME
      password:
        from_secret: SVC_CONTAINER_REGISTRY_PASSWORD
      repo: know-how.download/gripday/${DRONE_REPO_NAME}
      registry: know-how.download
      force_tag: true
      build_args:
        - BASE_IMAGE=know-how.download/library/nginx-runner
        - VCS_REFERENCE=${DRONE_COMMIT}
        - SOURCE_DIR=./docs/.vitepress/dist
      tags:
        - latest

---
kind: pipeline
name: DeployOnStaging
type: docker

trigger:
  event:
    - push
    - tag
  ref:
    - refs/heads/dev
    - refs/heads/prerelease/*
    - refs/heads/*.*.x
    - refs/tags/*
depends_on:
  - PublishArtifacts

volumes:
  - name: pnpm-store
    host:
      path: /app/.pnpm-store
steps:
  - name: deploy
    image: cicdtools/pipeline-runner
    pull: never
    environment:
      HELM_CHARTS_REPOSITORY:
        from_secret: HELM_CHARTS_REPOSITORY
      SVC_CONTAINER_REGISTRY_USERNAME:
        from_secret: SVC_CONTAINER_REGISTRY_USERNAME
      SVC_CONTAINER_REGISTRY_PASSWORD:
        from_secret: SVC_CONTAINER_REGISTRY_PASSWORD
    commands:
      - git clone $${HELM_CHARTS_REPOSITORY} charts && cd charts/services/${DRONE_REPO_NAME}
      - kubectl version --output=yaml
      - helm uninstall -n staging-env --ignore-not-found ${DRONE_REPO_NAME}
      - helm template ${DRONE_REPO_NAME} ./ --values ./values.yaml --values ./staging-values.yaml --set image.tag=latest -n staging-env
      - helm upgrade --install --atomic --wait --timeout 2m ${DRONE_REPO_NAME} ./ --values ./values.yaml --values ./staging-values.yaml --set image.tag=latest -n staging-env

  - name: notify-slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: dev
      template: >
        {{#success build.status}}
         :large_green_circle: :ship: *${DRONE_COMMIT_MESSAGE}*
         {{build.link}} ({{build.branch}}) by {{build.author}}
        {{else}}
         :red_circle: :anchor: {{build.link}} ({{build.branch}}) by {{build.author}}
        {{/success}}
    when:
      status:
        - failure
        - success
    depends_on:
      - deploy
